# Generated by Django 3.2.6 on 2021-08-10 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=65, verbose_name='remetente')),
                ('receiver', models.CharField(max_length=65, verbose_name='destinatário')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='e-mail do destinatário')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='hora de envio')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ('-created_at',),
            },
        ),
    ]
